name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build -t scb-project .

      - name: Run tests in Docker
        run: docker run --rm scb-project